### ISSUE TITLE
Format planner

### ISSUE THREAD

**Issue by tqwu** [fercevik729/UCSC-Course-Planner#51]
- Change quarter order to summer -> fall -> winter -> spring
- Change from freshman, sophomore, etc. to 1st, 2nd, ... nth year
- Responsive course planner grid
- Smaller padding around course titles
- Minimum height for quarter cards to compensate for 3 classes (adding more will make the quarter cards larger)
- Adjusting NavBar after logging in

**Comment by fercevik729** [comment]
Moved to milestone
